export const SOURCE_DEFINITIONS = {
  clinicaltrials_gov: {
    key: "clinicaltrials_gov",
    label: "ClinicalTrials.gov",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  sec_edgar: {
    key: "sec_edgar",
    label: "SEC EDGAR",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  openfda_drugsfda: {
    key: "openfda_drugsfda",
    label: "openFDA / Drugs@FDA",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  greenhouse: {
    key: "greenhouse",
    label: "Greenhouse Public Job Board",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  lever: {
    key: "lever",
    label: "Lever Public Postings",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  ashby: {
    key: "ashby",
    label: "Ashby Public Job Board",
    tier: "A",
    primary: true,
    mode: "api",
    implemented: true,
  },
  fda_adcom: {
    key: "fda_adcom",
    label: "FDA Advisory Committee Calendar",
    tier: "A",
    primary: true,
    mode: "web_research",
    implemented: false,
  },
  company_ir: {
    key: "company_ir",
    label: "Company Investor Relations",
    tier: "A",
    primary: true,
    mode: "web_research",
    implemented: false,
  },
  company_careers: {
    key: "company_careers",
    label: "Company Careers",
    tier: "A",
    primary: true,
    mode: "web_research",
    implemented: false,
  },
  fda_tracker: {
    key: "fda_tracker",
    label: "FDA Tracker",
    tier: "B",
    primary: false,
    mode: "web_research",
    implemented: false,
  },
  trade_press: {
    key: "trade_press",
    label: "Life-Sciences Trade Press",
    tier: "B",
    primary: false,
    mode: "web_research",
    implemented: false,
  },
  general_web: {
    key: "general_web",
    label: "Other Public Web",
    tier: "C",
    primary: false,
    mode: "web_research",
    implemented: false,
  },
};

export function getSourceDefinition(key) {
  return SOURCE_DEFINITIONS[key] || null;
}
